query searchUsers ($first: Int, $query: String!, $type: SearchType!) { 
  search(first: $first, query: $query, type: $type) {
    nodes {
      ... on Repository {
      	id
        name
        description
        owner {
          login
        }
      }
      ... on Organization {
        name
      }

      ... on User {
        id
        name
        bio
      }
    }
    userCount
  }
}
